/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBalanceSheetRouteImport } from './routes/_authenticated/balance-sheet'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMoneyInRouteImport } from './routes/_authenticated/money-in'
import { Route as AuthenticatedMoneyOutRouteImport } from './routes/_authenticated/money-out'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBalanceSheetRoute =
  AuthenticatedBalanceSheetRouteImport.update({
    id: '/balance-sheet',
    path: '/balance-sheet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyInRoute = AuthenticatedMoneyInRouteImport.update({
  id: '/money-in',
  path: '/money-in',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyOutRoute = AuthenticatedMoneyOutRouteImport.update({
  id: '/money-out',
  path: '/money-out',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balance-sheet': typeof AuthenticatedBalanceSheetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/money-in': typeof AuthenticatedMoneyInRoute
  '/money-out': typeof AuthenticatedMoneyOutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balance-sheet': typeof AuthenticatedBalanceSheetRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/money-in': typeof AuthenticatedMoneyInRoute
  '/money-out': typeof AuthenticatedMoneyOutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/balance-sheet': typeof AuthenticatedBalanceSheetRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/money-in': typeof AuthenticatedMoneyInRoute
  '/_authenticated/money-out': typeof AuthenticatedMoneyOutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/balance-sheet' | '/dashboard' | '/money-in' | '/money-out'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/balance-sheet' | '/dashboard' | '/money-in' | '/money-out'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/balance-sheet'
    | '/_authenticated/dashboard'
    | '/_authenticated/money-in'
    | '/_authenticated/money-out'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/balance-sheet': {
      id: '/_authenticated/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/balance-sheet'
      preLoaderRoute: typeof AuthenticatedBalanceSheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money-in': {
      id: '/_authenticated/money-in'
      path: '/money-in'
      fullPath: '/money-in'
      preLoaderRoute: typeof AuthenticatedMoneyInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money-out': {
      id: '/_authenticated/money-out'
      path: '/money-out'
      fullPath: '/money-out'
      preLoaderRoute: typeof AuthenticatedMoneyOutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBalanceSheetRoute: typeof AuthenticatedBalanceSheetRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMoneyInRoute: typeof AuthenticatedMoneyInRoute
  AuthenticatedMoneyOutRoute: typeof AuthenticatedMoneyOutRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBalanceSheetRoute: AuthenticatedBalanceSheetRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMoneyInRoute: AuthenticatedMoneyInRoute,
  AuthenticatedMoneyOutRoute: AuthenticatedMoneyOutRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
